# Generated by Django 5.1.3 on 2024-12-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='profile_imgs')),
                ('age', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='Home',
        ),
    ]
