# Generated by Django 5.1.3 on 2024-12-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_profile_delete_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top_Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_icon', models.ImageField(upload_to='category_icons')),
                ('category_name', models.CharField(max_length=128)),
                ('category_course_counts', models.CharField(max_length=128)),
            ],
        ),
    ]
