# Generated by Django 5.1.3 on 2024-12-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_top_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top_Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='courses/course_thumbnails')),
                ('title', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=128)),
                ('rating_star', models.ImageField(upload_to='courses/course_rating_stars')),
            ],
        ),
        migrations.RenameField(
            model_name='top_categories',
            old_name='category_course_counts',
            new_name='course_counts',
        ),
        migrations.RenameField(
            model_name='top_categories',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='top_categories',
            name='category_icon',
        ),
        migrations.AddField(
            model_name='top_categories',
            name='icon',
            field=models.ImageField(default='icon', upload_to='categories/category_icons'),
            preserve_default=False,
        ),
    ]
