# Generated by Django 5.1.3 on 2024-12-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_top_courses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top_Instructors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_image', models.ImageField(upload_to='instructors/instructor_images')),
                ('name', models.CharField(max_length=128)),
                ('course_name', models.CharField(max_length=128)),
                ('rating_text', models.CharField(max_length=128)),
                ('students_enrolled_count', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='top_courses',
            name='course_hours',
            field=models.CharField(default='one', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='top_courses',
            name='course_level',
            field=models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advanced')], default='one', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='top_courses',
            name='lecture_counts',
            field=models.CharField(default='one', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='top_courses',
            name='price',
            field=models.CharField(default='one', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='top_courses',
            name='rating_text',
            field=models.CharField(default='one', max_length=128),
            preserve_default=False,
        ),
    ]
