# Generated by Django 5.1.3 on 2024-12-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_top_instructors_top_courses_course_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=536)),
                ('image', models.ImageField(upload_to='customer_feedbacks/customer_images')),
                ('name', models.CharField(max_length=128)),
                ('profession', models.CharField(max_length=128)),
            ],
        ),
    ]
