# Generated by Django 5.1.3 on 2024-12-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_top_instructors_rating_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_feedback',
            name='text',
            field=models.TextField(),
        ),
    ]
