# Generated by Django 5.1.3 on 2024-12-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_customer_feedback_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='top_courses',
            name='course_decription',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
    ]
