# Generated by Django 5.1.3 on 2024-12-11 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_top_courses_course_languages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='top_courses',
            old_name='course_decription',
            new_name='course_description',
        ),
    ]
