# Generated by Django 5.1.3 on 2024-12-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_rename_course_decription_top_courses_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='top_courses',
            name='rating_single_star',
            field=models.ImageField(default='1', upload_to='courses/course_rating_stars'),
            preserve_default=False,
        ),
    ]
