# Generated by Django 5.1.3 on 2024-12-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_top_courses_rating_single_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='top_courses',
            name='rating_five_out_of',
            field=models.CharField(default='1', max_length=128),
            preserve_default=False,
        ),
    ]
