# Generated by Django 5.1.3 on 2024-12-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_top_courses_author_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='top_courses',
            name='course_thumbnail',
            field=models.ImageField(default='1', upload_to='courses/course_detail_thumbnails'),
            preserve_default=False,
        ),
    ]
