# Generated by Django 5.1.3 on 2024-12-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_top_courses_course_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='top_courses',
            name='strike_out_price',
            field=models.CharField(default='1', max_length=128),
            preserve_default=False,
        ),
    ]
