# Generated by Django 5.1.3 on 2024-12-11 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_top_courses_strike_out_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='top_courses',
            old_name='course_thumbnail',
            new_name='course_detail_thumbnail',
        ),
    ]
