# Generated by Django 5.1.3 on 2024-12-16 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_purchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
